const TYPES = {
  // 系统相关
  SAVE_LOGIN_USER: "SAVE_LOGIN_USER",
  LOAD_LOGIN_USER: "LOAD_LOGIN_USER",
  LOGINOUT_USER: "LOGINOUT_USER",
  ALERT_MESSAGE: "ALERT_MESSAGE",
  OPEN_WIN_MODEL: "OPEN_WIN_MODEL",
  NOTICE_MESSAGE: "NOTICE_MESSAGE",
  GOTO_PAGE: "GOTO_PAGE",
  CLOSE_PAGE: "CLOSE_PAGE",
  UPDATE_LOADING_MODEL_VISIBLE: "UPDATE_LOADING_MODEL_VISIBLE",
  // AccountInfo模块
  ACCOUNT_INFO_REFRESH_DATA: "ACCOUNT_INFO_REFRESH_DATA",
  //注册码
  REGISTER_CODE: "REGISTER_CODE",
  //common-公告
  COMMON_GONGGAO: "COMMON_GONGGAO",
  // sessionToken
  SESSION_TOKEN: "SESSION_TOKEN",
  // 系统配置信息
  SYSTEM_SETTINGS: "SYSTEM_SETTINGS",
  // 快速路由
  BASE_URL: '@BASE_URL',
  // 本地路由表
  BASE_URL_LIST: '&BASE_URL_LIST&',
  // 本地路由表
  CHANGE_URL: 'CHANGE_URL',
  // 系统信息刷新
  SYSTEM_UPDATE: 'SYSTEM_UPDATE',
  // 本地路由表
  SET_FASTURL: 'SET_FASTURL',
  // 系统图片
  SYS_PIC: 'SYS_PIC',
  WEBNAV: 'WEBNAV',
  CHANGE_TAB:'CHANGE_TAB'
};

export default TYPES;
